### ISSUE TITLE
Data race in crossbeam-deque

### ISSUE THREAD

**Issue by youjiali1995** [tikv/yatp#55]
See https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-pqqp-xmhj-wgcw. We should update `crossbeam-deque`.

**Comment by BusyJay** [comment]
Nothing needs to be done for yatp as it uses 0.8 already.

**Comment by BusyJay** [comment]
Close as it's not related to yatp. TiKV has also updated the dependencies in release versions.
